import type {Env} from './types';
import type {Admin} from '../shared/contracts';
import {ApiError,body,json} from './http';
import {requireStudent,requireAdmin} from './session';
import {ownOrder,serializeOrder} from './orders';
import {orderScope} from './order-access';
import {orderActionSchema} from '../shared/delivery';
import {ticketCreate,ticketReply,ticketState,type Ticket} from '../shared/support';
import {rateLimit} from './rate-limit';
import {z} from 'zod';
const cols=`t.id,t.order_id AS orderId,t.user_id AS userId,t.category,t.subject,t.status,t.version,t.created_at AS createdAt,o.status AS linkedStatus,json_extract(o.dorm_snapshot_json,'$.buildingName') AS linkedBuilding,json_extract(o.dorm_snapshot_json,'$.roomNo') AS linkedRoom,json_extract(o.station_snapshot_json,'$.canonicalName') AS linkedStation`;
interface TicketRow extends Ticket {linkedStatus:NonNullable<Ticket['orderContext']>['status'];linkedBuilding:string;linkedRoom:string;linkedStation:string}
function ticketView(row:TicketRow):Ticket{const {linkedStatus,linkedBuilding,linkedRoom,linkedStation,...ticket}=row;return {...ticket,orderContext:{status:linkedStatus,building:linkedBuilding,room:linkedRoom,station:linkedStation}};}
function ticketScope(actor:{id:string},admin?:Admin){const scope=admin?orderScope(admin):{sql:'o.user_id=?',params:[actor.id]};return scope;}
async function readTicket(env:Env,id:string,actor:{id:string},admin?:Admin){const scope=ticketScope(actor,admin);const row=await env.DB.prepare(`SELECT ${cols} FROM support_tickets t JOIN delivery_orders o ON o.id=t.order_id WHERE t.id=? AND ${scope.sql}`).bind(id,...scope.params).first<TicketRow>();if(!row)throw new ApiError(404,'NOT_FOUND','工单不存在或无权访问');return ticketView(row);}
export async function serviceRoutes(request:Request,env:Env){
 const path=new URL(request.url).pathname.replace('/api/v1',''),method=request.method;
 const receipt=/^\/orders\/([a-f0-9-]{36})\/receive$/.exec(path);
 if(receipt&&method==='POST'){const u=await requireStudent(request,env),d=await body(request,orderActionSchema),o=await ownOrder(env,u.id,receipt[1]);if(o.status==='COMPLETED')return json({order:serializeOrder(o)});
 if(!['DELIVERED_DOWNSTAIRS','DELIVERED_TO_ROOM'].includes(o.status))throw new ApiError(409,'NOT_DELIVERED','配送员标记送达后才能确认收货');
 const r=await env.DB.prepare("UPDATE delivery_orders SET status='COMPLETED',received_at=unixepoch(),version=version+1,last_actor_type='STUDENT',last_actor_id=?,updated_at=unixepoch() WHERE id=? AND user_id=? AND version=? AND student_deleted=0 AND status IN ('DELIVERED_DOWNSTAIRS','DELIVERED_TO_ROOM')").bind(u.id,o.id,u.id,d.version).run();if(!r.meta.changes)throw new ApiError(409,'STALE_ORDER','订单已变化，请刷新');return json({order:serializeOrder(await ownOrder(env,u.id,o.id))});}
 if(path==='/messages'||path.startsWith('/messages/')){const u=await requireStudent(request,env);
 if(path==='/messages'&&method==='GET'){const raw=new URL(request.url).searchParams.get('before'),before=raw?Number(raw):Number.MAX_SAFE_INTEGER;if(!Number.isSafeInteger(before)||before<=0)throw new ApiError(400,'INVALID_CURSOR','分页参数无效');const rows=(await env.DB.prepare('SELECT id,order_id AS orderId,kind,title,read_at AS readAt,created_at AS createdAt FROM inbox_messages WHERE user_id=? AND id<? ORDER BY id DESC LIMIT 31').bind(u.id,before).all()).results;const unread=await env.DB.prepare('SELECT count(*) AS n FROM inbox_messages WHERE user_id=? AND read_at IS NULL').bind(u.id).first('n');return json({messages:rows.slice(0,30),nextCursor:rows.length>30?rows[29].id:null,unread});}
 if(path==='/messages/read-all'&&method==='POST'){await body(request,z.object({confirmed:z.literal(true)}).strict());await env.DB.prepare('UPDATE inbox_messages SET read_at=unixepoch() WHERE user_id=? AND read_at IS NULL').bind(u.id).run();return json({ok:true});}
 const read=/^\/messages\/(\d+)\/read$/.exec(path);if(read&&method==='POST'){await env.DB.prepare('UPDATE inbox_messages SET read_at=COALESCE(read_at,unixepoch()) WHERE id=? AND user_id=?').bind(Number(read[1]),u.id).run();return json({ok:true});}
 }
 const adminPath=path.startsWith('/admin/tickets');if(path==='/tickets'||path.startsWith('/tickets/')||adminPath){
 const admin=adminPath?await requireAdmin(request,env):undefined,actor=admin??await requireStudent(request,env),base=adminPath?'/admin/tickets':'/tickets';
 if(path===base&&method==='GET'){const scope=ticketScope(actor,admin),q=new URL(request.url).searchParams,before=q.get('before');if(before&&!/^\d+_[a-f0-9-]{36}$/.test(before))throw new ApiError(400,'INVALID_CURSOR','工单分页无效');const [time,id]=before?.split('_')??[];const rows=(await env.DB.prepare(`SELECT ${cols} FROM support_tickets t JOIN delivery_orders o ON o.id=t.order_id WHERE ${scope.sql} ${before?'AND (t.created_at<? OR (t.created_at=? AND t.id<?))':''} ORDER BY t.created_at DESC,t.id DESC LIMIT 31`).bind(...scope.params,...(before?[Number(time),Number(time),id]:[])).all<TicketRow>()).results;return json({tickets:rows.slice(0,30).map(ticketView),nextCursor:rows.length>30?`${rows[29].createdAt}_${rows[29].id}`:null});}
 if(path===base&&method==='POST'&&!admin){await rateLimit(env,`ticket:${actor.id}`,10);const d=await body(request,ticketCreate);await ownOrder(env,actor.id,d.orderId,true);const id=crypto.randomUUID();try{await env.DB.batch([env.DB.prepare('INSERT INTO support_tickets(id,order_id,user_id,category,subject) VALUES(?,?,?,?,?)').bind(id,d.orderId,actor.id,d.category,d.subject),env.DB.prepare("INSERT INTO ticket_messages(ticket_id,actor_kind,actor_id,body) VALUES(?,'STUDENT',?,?)").bind(id,actor.id,d.body)]);}catch(e){if(String(e).includes('UNIQUE constraint'))throw new ApiError(409,'TICKET_EXISTS','该订单已有未关闭工单，请在售后列表继续沟通');throw e;}return json({ticket:await readTicket(env,id,actor)},201);}
 const match=/^\/(?:admin\/)?tickets\/([a-f0-9-]{36})(?:\/(messages|status))?$/.exec(path);if(match){const id=match[1],ticket=await readTicket(env,id,actor,admin),scope=ticketScope(actor,admin);
 if(!match[2]&&method==='GET'){const msgs=await env.DB.prepare('SELECT id,actor_kind AS actorKind,body,created_at AS createdAt FROM ticket_messages WHERE ticket_id=? ORDER BY id DESC LIMIT 200').bind(id).all();return json({ticket,messages:msgs.results.reverse()});}
 if(match[2]==='messages'&&method==='POST'){await rateLimit(env,`ticket-message:${actor.id}`,60);const d=await body(request,ticketReply);if(ticket.status==='CLOSED')throw new ApiError(409,'TICKET_CLOSED','工单已关闭');const r=await env.DB.prepare(`INSERT INTO ticket_messages(ticket_id,actor_kind,actor_id,body) SELECT t.id,?,?,? FROM support_tickets t JOIN delivery_orders o ON o.id=t.order_id WHERE t.id=? AND t.version=? AND t.status<>'CLOSED' AND ${scope.sql}`).bind(admin?'ADMIN':'STUDENT',actor.id,d.body,id,d.version,...scope.params).run();if(!r.meta.changes)throw new ApiError(409,'STALE_TICKET','工单已变化，请刷新后回复');return json({ok:true});}
 if(match[2]==='status'&&method==='POST'){const d=await body(request,ticketState);const permitted=admin?(ticket.status==='OPEN'&&d.status==='IN_PROGRESS')||(ticket.status==='IN_PROGRESS'&&d.status==='RESOLVED'):(ticket.status==='RESOLVED'&&['CLOSED','OPEN'].includes(d.status));if(d.status==='RESOLVED'&&!await env.DB.prepare("SELECT id FROM ticket_messages WHERE ticket_id=? AND actor_kind='ADMIN' LIMIT 1").bind(id).first())throw new ApiError(409,'REPLY_REQUIRED','请先回复处理方案，再标记已解决');if(!permitted)throw new ApiError(409,'INVALID_TRANSITION','不能这样推进工单；管理员受理并解决后，由学生关闭或重新打开');const r=await env.DB.batch([env.DB.prepare(`UPDATE support_tickets SET status=?,version=version+1,updated_at=unixepoch() WHERE id=? AND version=? AND EXISTS(SELECT 1 FROM delivery_orders o WHERE o.id=support_tickets.order_id AND ${scope.sql})`).bind(d.status,id,d.version,...scope.params),env.DB.prepare("INSERT INTO audit_logs(id,actor_type,actor_id,action,resource_id) SELECT ?,?,?,'TICKET_STATUS_UPDATED',? WHERE changes()>0").bind(crypto.randomUUID(),admin?'ADMIN':'STUDENT',actor.id,id)]);if(!r[0].meta.changes)throw new ApiError(409,'STALE_TICKET','工单已变化，请刷新');return json({ok:true});}
 }
 }
 return null;
}
