import {RoundHistory,BulkPickupView} from './service-pages';
import { ConfirmAction,AdminTaskTable,SensitiveValue,LoadingState,EmptyState } from './components';
import { useEffect,useState,type FormEvent,type ReactNode } from 'react';
import { Link,NavLink,Navigate,useParams } from 'react-router-dom';
import { HandoffPanel } from './handoff-panel';
import type { AvailableOrder } from '../shared/delivery';
import type { Admin,AdminRole,Building } from '../shared/contracts';
import { CAMPUS_ID } from '../shared/contracts';
import { nextStatuses } from '../domain/commerce';
import { TASK_GROUP_LABELS,STATUS_LABELS,type Order,type OrderStatus } from '../shared/delivery';
import { api } from './api';
import { money,useResource } from './student-delivery';
export function AdminShell({children}:{children:ReactNode}){const me=useResource<{admin:Admin}>('/admin/me');if(me.loading&&!me.data)return <LoadingState/>;if(me.error)return <section><h1>请先登录管理员</h1><p role="alert">{me.error}</p><Link to="/admin/login">管理员登录</Link></section>;if(me.data&&!me.data.admin.phone)return <Navigate to="/admin/account" replace/>;return <section className="admin-section"><aside className="admin-sidebar"><p className="eyebrow">CAMPUSDROP / 工作空间</p><nav className="admin-nav" aria-label="管理员导航"><NavLink to="/admin" end>配送任务</NavLink><NavLink to="/admin/batches">批次管理</NavLink><NavLink to="/admin/tickets">售后工单</NavLink>{me.data?.admin.role==='SUPER_ADMIN'&&<><NavLink to="/admin/admins">管理员</NavLink><NavLink to="/admin/audit">审计日志</NavLink><NavLink to="/admin/recovery">账号恢复</NavLink><NavLink to="/admin/errors">错误监控</NavLink></>}<NavLink to="/admin/account">我的授权</NavLink></nav><p className="muted">一人一号 · 授权范围内协作</p></aside><div className="admin-content">{children}</div></section>;}
export function TaskCard({order,refresh,select,onSelect}:{order:Order;refresh:()=>Promise<void>;select?:boolean;onSelect?:(checked:boolean)=>void}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState('OTHER'),[detail,setDetail]=useState(''),[exception,setException]=useState<OrderStatus|null>(null),[releaseReason,setReleaseReason]=useState('');
  useEffect(()=>{setException(null);setDetail('');setReleaseReason('');},[order.id,order.version]);
  async function advance(status:OrderStatus){setBusy(true);try{if(status==='CANCELLED')await api(`/admin/orders/${order.id}/release`,'POST',{version:order.version,confirmed:true,reason:releaseReason.trim()});else await api(`/admin/orders/${order.id}/status`,'PATCH',{status,version:order.version,...(['FAILED_PICKUP','DELIVERY_EXCEPTION'].includes(status)?{exceptionCode:reason,exceptionNote:detail}:{})});setError('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <article className="parcel-card task-card" data-order-id={order.id}><div className="row"><strong>{order.dormSnapshot.buildingName} · {order.dormSnapshot.roomNo}</strong><span className="badge">{STATUS_LABELS[order.status]}</span></div>
    <p>{order.packageSize==='SMALL'?'小件':'大件'} / {order.deliveryMode==='ROOM'?'到寝':'楼下'} · {money(order.amountFen)}</p><p className="muted">{order.stationSnapshot.canonicalName} · 联系电话 {order.dormSnapshot.phone}</p><p>备注：{order.note||'暂无备注'}</p>{order.exceptionNote&&<p role="alert">问题说明：{order.exceptionNote}</p>}
    {onSelect&&order.status==='WAITING_PICKUP'&&<label className="check"><input type="checkbox" checked={select} onChange={e=>onSelect(e.target.checked)}/>加入取件批次</label>}
    {!['COMPLETED','CANCELLED'].includes(order.status)&&<SensitiveValue orderId={order.id} version={order.version}/>}
    {exception&&<div className="exception-form"><h3>{STATUS_LABELS[exception]}说明</h3><label htmlFor={`reason-${order.id}`}>异常原因</label><select id={`reason-${order.id}`} value={reason} onChange={e=>setReason(e.target.value)}><option value="OTHER">其他异常</option><option value="CODE_INVALID">取件码无效</option><option value="SIZE_MISMATCH">大小件不符</option><option value="UNREACHABLE">无法联系</option></select><label>问题说明（选填，学生可见）<textarea maxLength={240} value={detail} onChange={e=>setDetail(e.target.value)} placeholder="例如：包裹不在货架、寝室无人接收"/></label><div className="actions"><button disabled={busy} onClick={()=>void advance(exception)}>确认标记</button><button className="secondary" disabled={busy} onClick={()=>{setException(null);setDetail('');}}>取消标记</button></div></div>}
    <RoundHistory order={order}/><HandoffPanel order={order} refresh={refresh}/><div className="actions task-actions">{nextStatuses(order.status,order.deliveryMode).filter(s=>s!=='COMPLETED').map(s=>s==='CANCELLED'?<ConfirmAction key={s} label="退回接单市场" title="确认退回接单市场？" canConfirm={releaseReason.trim().length>0} validationMessage="请填写退回理由，学生和下一位接单人都会看到。" busy={busy} onConfirm={()=>advance(s)}><p>学生会看到退单原因，其他配送员可以重新接单。若已取到包裹，请先完成交接或放回取件站点。</p><label>退单说明<textarea maxLength={240} value={releaseReason} onChange={e=>setReleaseReason(e.target.value)}/></label></ConfirmAction>:<button key={s} className={['CANCELLED','FAILED_PICKUP','DELIVERY_EXCEPTION'].includes(s)?'secondary':''} disabled={busy} onClick={()=>{if(['FAILED_PICKUP','DELIVERY_EXCEPTION'].includes(s)){setException(s);setDetail('');setReason('OTHER');}else void advance(s);}}>{STATUS_LABELS[s]}</button>)}</div><p role="status">{error}</p>
  </article>;
}
function AvailableTasks({onClaim,revision}:{onClaim:()=>Promise<void>;revision:number}){
 const [cursor,setCursor]=useState(''),[back,setBack]=useState<string[]>([]),[building,setBuilding]=useState(''),[size,setSize]=useState(''),[mode,setMode]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const query=new URLSearchParams({pageSize:'12',...(cursor?{cursor}:{}),...(building?{building}:{}),...(size?{packageSize:size}:{}),...(mode?{deliveryMode:mode}:{})});
 const resource=useResource<{orders:AvailableOrder[];nextCursor:string|null;hasMore:boolean}>(`/admin/available?${query}`),buildings=useResource<{buildings:Building[]}>('/dorm-buildings');
 useEffect(()=>{void resource.refresh();},[revision,resource.refresh]);
 function reset(){setCursor('');setBack([]);}
 async function claim(id:string){setBusy(true);try{await api(`/admin/orders/${id}/claim`,'POST',{confirmed:true});setMessage('接单成功，已加入我的任务');await onClaim();}catch(e){setMessage((e as Error).message);}finally{await resource.refresh();setBusy(false);}}
 return <section><div className="row"><h2>待接订单</h2><button className="text-button" onClick={()=>{reset();void resource.refresh();}}>刷新待接订单</button></div><p>服务端筛选 · 每页12条 · 接单后才显示联系方式与取件码。</p><div className="filters"><label>市场楼栋<select value={building} onChange={e=>{setBuilding(e.target.value);reset();}}><option value="">全部授权范围</option>{buildings.data?.buildings.map(b=><option key={b.code} value={b.code}>{b.displayName}</option>)}</select></label><label>市场包裹大小<select value={size} onChange={e=>{setSize(e.target.value);reset();}}><option value="">全部</option><option value="SMALL">小件</option><option value="LARGE">大件</option></select></label><label>市场配送方式<select value={mode} onChange={e=>{setMode(e.target.value);reset();}}><option value="">全部</option><option value="ROOM">到寝</option><option value="DOWNSTAIRS">楼下</option></select></label></div><p role="status">{message}</p><p role="alert">{resource.error}</p>{resource.loading&&!resource.data&&<LoadingState/>}<div className="card-list market-grid">{resource.data?.orders.map(o=><article className="parcel-card" data-order-id={o.id} key={o.id}><strong>{o.buildingName}</strong><p>{o.stationName}</p><p>{o.packageSize==='SMALL'?'小件':'大件'} · {o.deliveryMode==='ROOM'?'到寝':'楼下'} · {money(o.amountFen)}</p><button disabled={busy} onClick={()=>void claim(o.id)}>接单</button></article>)}</div>{resource.data?.orders.length===0&&<p>本页暂无待接订单，请刷新或调整筛选。</p>}<div className="actions"><button className="secondary" disabled={!back.length} onClick={()=>{setCursor(back.at(-1)!);setBack(back.slice(0,-1));}}>待接上一页</button><span>第 {back.length+1} 页</span><button className="secondary" disabled={!resource.data?.nextCursor} onClick={()=>{setBack([...back,cursor]);setCursor(resource.data!.nextCursor!);}}>待接下一页</button></div></section>;
}
export function AdminTasks(){
  const [marketRevision,setMarketRevision]=useState(0);
  const [filters,setFilters]=useState({group:'ALL',status:'',building:'',packageSize:'',deliveryMode:''});
  const [cursor,setCursor]=useState(''),[back,setBack]=useState<string[]>([]);
  const page=back.length+1;function setPage(next:number){if(next===1){setCursor('');setBack([]);}else if(next<page){setCursor(back.at(-1)!);setBack(back.slice(0,-1));}else if(tasks.data?.nextCursor){setBack([...back,cursor]);setCursor(tasks.data.nextCursor);}}
  const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));query.set('pageSize','30');if(cursor)query.set('cursor',cursor);
  const tasks=useResource<{orders:Order[];nextCursor:string|null}>(`/admin/tasks?${query}`),me=useResource<{admin:Admin}>('/admin/me');
  const buildings=useResource<{buildings:Building[]}>('/admin/dorm-buildings');
  const stats=useResource<{counts:{status:OrderStatus;count:number}[]}>('/admin/dashboard');
  const [selected,setSelected]=useState<string[]>([]),[assignee,setAssignee]=useState(''),[assignees,setAssignees]=useState<{id:string;username:string}[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{if(me.data&&me.data.admin.role!=='DELIVERY_STAFF')api<{admins:{id:string;username:string}[]}>('/admin/assignees').then(r=>{setAssignees(r.admins);setAssignee(me.data!.admin.id);}).catch(e=>setMessage(e.message));},[me.data]);
  async function refresh(){setMarketRevision(v=>v+1);setSelected([]);await tasks.refresh();await stats.refresh();}
  async function batch(){setBusy(true);try{await api('/admin/batches','POST',{orderIds:selected,assigneeAdminId:assignee});setMessage('批次已创建，可前往批次管理查看');await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <AdminShell><h1>配送工作台</h1><AvailableTasks onClaim={refresh} revision={marketRevision}/><h2>我的授权任务</h2><p className="muted">模拟订单 · 只显示你负责的任务</p><div className="stats">{stats.data?.counts.map(c=><span key={c.status}>{STATUS_LABELS[c.status]} <strong>{c.count}</strong></span>)}</div>
    <div className="filters"><div><label htmlFor="task-group">订单分类</label><select id="task-group" value={filters.group} onChange={e=>{setFilters({...filters,group:e.target.value,status:''});setPage(1);setSelected([]);}}>{Object.entries(TASK_GROUP_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div><label htmlFor="task-status">具体状态</label><select id="task-status" disabled={filters.group!=='ALL'} value={filters.status} onChange={e=>{setFilters({...filters,status:e.target.value});setPage(1);setSelected([]);}}><option value="">全部已支付任务</option>{Object.entries(STATUS_LABELS).filter(([k])=>k!=='WAITING_PAYMENT').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
      <label>楼栋<select value={filters.building} onChange={e=>{setFilters({...filters,building:e.target.value});setPage(1);setSelected([]);}}><option value="">全部授权楼栋</option>{buildings.data?.buildings.map(b=><option key={b.code} value={b.code}>{b.displayName}</option>)}</select></label>
      <label>大小件<select value={filters.packageSize} onChange={e=>{setFilters({...filters,packageSize:e.target.value});setPage(1);setSelected([]);}}><option value="">全部</option><option value="SMALL">小件</option><option value="LARGE">大件</option></select></label>
      <label>配送方式<select value={filters.deliveryMode} onChange={e=>{setFilters({...filters,deliveryMode:e.target.value});setPage(1);setSelected([]);}}><option value="">全部</option><option value="ROOM">到寝</option><option value="DOWNSTAIRS">楼下</option></select></label></div>
    <p role="alert">{tasks.error||me.error||buildings.error||stats.error}</p>{(tasks.error||me.error)&&<Link to="/admin/login">管理员登录</Link>}
    {me.data?.admin.role!=='DELIVERY_STAFF'&&assignees.length>0&&<div className="batch-tools"><button className="secondary" disabled={busy} onClick={()=>setSelected((tasks.data?.orders??[]).filter(o=>o.status==='WAITING_PICKUP').slice(0,20).map(o=>o.id))}>全选本页待取件（最多20单）</button><button className="text-button" disabled={busy} onClick={()=>setSelected([])}>清空批次选择</button><label htmlFor="batch-assignee">批次负责人</label><select id="batch-assignee" value={assignee} onChange={e=>setAssignee(e.target.value)}>{assignees.map(a=><option key={a.id} value={a.id}>{a.username}</option>)}</select><button disabled={busy||selected.length===0||selected.length>20} onClick={()=>void batch()}>生成取件批次（{selected.length}/20）</button></div>}
    <p role="status">{message}</p>{tasks.loading&&!tasks.data&&<LoadingState/>}{tasks.data?.orders.length===0&&<EmptyState title="当前任务已清空"><p>暂无符合筛选条件的订单，可以调整筛选或稍后刷新。</p></EmptyState>}
    <BulkPickupView orders={tasks.data?.orders??[]}/><AdminTaskTable orders={tasks.data?.orders??[]} renderTask={o=><TaskCard key={o.id} order={o} refresh={refresh} select={selected.includes(o.id)} onSelect={me.data?.admin.role==='DELIVERY_STAFF'?undefined:checked=>setSelected(checked?(selected.length<20?[...selected,o.id]:selected):selected.filter(id=>id!==o.id))}/>}/>
    <div className="actions"><button className="secondary" disabled={page===1} onClick={()=>{setPage(page-1);setSelected([]);}}>上一页</button><span>第 {page} 页</span><button className="secondary" disabled={!tasks.data?.nextCursor} onClick={()=>{setPage(page+1);setSelected([]);}}>下一页</button><button className="text-button" onClick={()=>void refresh()}>刷新任务</button></div>
  </AdminShell>;
}
export function Batches(){
  const {data,error,loading}=useResource<{batches:{id:string;stationCode:string;assigneeName:string;orderCount:number}[]}>('/admin/batches');
  return <AdminShell><h1>取件与配送批次</h1><p role="alert">{error}</p>{loading&&!data&&<LoadingState/>}{data?.batches.length===0&&<p>还没有批次，请在配送任务中勾选待取件订单。</p>}<div className="card-list">{data?.batches.map(b=><article className="parcel-card" key={b.id}><strong>{b.assigneeName} · {b.orderCount} 单</strong><p>站点 {b.stationCode}</p><Link to={`/admin/batches/${b.id}`}>打开批次</Link></article>)}</div></AdminShell>;
}
export function BatchDetail(){
  const {id}=useParams();const resource=useResource<{orders:Order[]}>(`/admin/batches/${id}`);const [detail,setDetail]=useState(''),[status,setStatus]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const orders=resource.data?.orders??[];const common=orders.length?nextStatuses(orders[0].status,orders[0].deliveryMode).filter(s=>s!=='CANCELLED'&&s!=='COMPLETED').filter(s=>orders.every(o=>nextStatuses(o.status,o.deliveryMode).includes(s))):[];
  async function apply(){setBusy(true);try{const r=await api<{results:{ok:boolean}[]}>(`/admin/batches/${id}/status`,'PATCH',{status,versions:Object.fromEntries(orders.map(o=>[o.id,o.version])),...(['FAILED_PICKUP','DELIVERY_EXCEPTION'].includes(status)?{exceptionCode:'OTHER',exceptionNote:detail}:{})});setMessage(`成功 ${r.results.filter(x=>x.ok).length} 单；未更新 ${r.results.filter(x=>!x.ok).length} 单。未更新的订单请刷新后逐单检查。`);setStatus('');await resource.refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <AdminShell><h1>批次详情</h1><p>按区域和楼栋排列。仅操作当前授权范围内的订单。</p><p role="alert">{resource.error}</p>{resource.loading&&!resource.data&&<LoadingState/>}<label htmlFor="batch-next">批量推进</label><select id="batch-next" value={status} onChange={e=>setStatus(e.target.value)}><option value="">选择共同的下一状态</option>{common.map(s=><option key={s} value={s}>{STATUS_LABELS[s]}</option>)}</select>{['FAILED_PICKUP','DELIVERY_EXCEPTION'].includes(status)&&<label>本批次问题说明<textarea maxLength={240} value={detail} onChange={e=>setDetail(e.target.value)}/></label>}<button disabled={!status||busy} onClick={()=>void apply()}>更新本批次</button><p role="status">{message}</p><div className="task-grid">{orders.map(o=><TaskCard key={o.id} order={o} refresh={resource.refresh}/>)}</div></AdminShell>;
}
export function AdminAccounts(){
  const list=useResource<{admins:{id:string;username:string;role:AdminRole;status:string}[]}>('/admin/admins');const buildings=useResource<{buildings:Building[]}>('/dorm-buildings');
  const [role,setRole]=useState<AdminRole>('ZONE_ADMIN'),[zone,setZone]=useState<'SOUTH'|'NORTH'>('SOUTH'),[codes,setCodes]=useState<string[]>([]),[editing,setEditing]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget);
    const scopes=role==='SUPER_ADMIN'||role==='DELIVERY_STAFF'?[]:role==='ZONE_ADMIN'?[{campusId:CAMPUS_ID,zone,buildingCode:null}]:codes.map(code=>({campusId:CAMPUS_ID,zone:code.startsWith('SOUTH')?'SOUTH':'NORTH',buildingCode:code}));
    try{await api(editing?`/admin/admins/${editing}/scopes`:'/admin/admins',editing?'PUT':'POST',{role,scopes,...(!editing?{username:form.get('username'),password:form.get('password')}:{})});setMessage('管理员设置已保存');setEditing('');await list.refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function disable(id:string){try{await api(`/admin/admins/${id}/disable`,'POST');await list.refresh();}catch(e){setMessage((e as Error).message);}}
  return <AdminShell><h1>管理员与授权</h1><p role="alert">{list.error}</p>{list.loading&&!list.data&&<LoadingState/>}{list.data&&<><div className="card-list">{list.data.admins.map(a=><article key={a.id} className="parcel-card"><strong>{a.username}</strong><p>{a.role} · {a.status}</p><div className="actions">{a.role!=='SUPER_ADMIN'&&<><button className="secondary" onClick={()=>{setEditing(a.id);setRole(a.role);setCodes([]);}}>重新分配权限</button><button className="secondary" disabled={a.status==='DISABLED'} onClick={()=>void disable(a.id)}>停用账号</button></>}</div></article>)}</div>
    <h2>{editing?'重新分配权限':'创建管理员'}</h2><form onSubmit={save}>{!editing&&<><label>新管理员用户名<input name="username" required minLength={3} maxLength={32}/></label><label>新管理员密码<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label></>}
      <label htmlFor="admin-role">角色</label><select id="admin-role" value={role} onChange={e=>{setRole(e.target.value as AdminRole);setCodes([]);}}>{(['SUPER_ADMIN','ZONE_ADMIN','BUILDING_ADMIN','DELIVERY_STAFF'] as const).map(r=><option key={r}>{r}</option>)}</select>
      {role==='ZONE_ADMIN'&&<><label htmlFor="admin-zone">负责区域</label><select id="admin-zone" value={zone} onChange={e=>setZone(e.target.value as 'SOUTH'|'NORTH')}><option value="SOUTH">南苑</option><option value="NORTH">北苑</option></select></>}
      {role==='BUILDING_ADMIN'&&<fieldset><legend>负责楼栋</legend>{buildings.data?.buildings.map(b=><label className="check" key={b.code}><input type="checkbox" checked={codes.includes(b.code)} onChange={e=>setCodes(e.target.checked?[...codes,b.code]:codes.filter(c=>c!==b.code))}/>{b.displayName}</label>)}</fieldset>}
      <button disabled={busy}>{busy?'保存中…':'保存管理员'}</button>{editing&&<button type="button" className="text-button" onClick={()=>setEditing('')}>取消修改</button>}
    </form></>}<p role="status">{message}</p></AdminShell>;
}
export function Audit(){
  const {data,error,loading}=useResource<{logs:{id:string;action:string;actorId:string;resourceId:string;metadata:string;createdAt:number}[]}>('/admin/audit');
  return <AdminShell><h1>操作审计</h1><p>展示最近 100 条，取件码只保留脱敏值。</p><p role="alert">{error}</p>{loading&&!data&&<LoadingState/>}{data?.logs.length===0&&<EmptyState title="还没有审计记录"/>}<div className="card-list">{data?.logs.map(log=><article className="parcel-card" key={log.id}><strong>{log.action}</strong><small>{new Date(log.createdAt*1000).toLocaleString()}</small><p className="identifier">操作者：{log.actorId}</p><p className="identifier">资源：{log.resourceId}</p><code>{log.metadata}</code></article>)}</div></AdminShell>;
}

export function AdminOrderDetail(){const {id}=useParams();const r=useResource<{order:Order}>(`/admin/orders/${id}`);return <AdminShell><h1>订单详情</h1><Link to="/admin/tickets">返回售后工作台</Link><p role="alert">{r.error}</p>{r.loading&&!r.data&&<LoadingState/>}{r.data&&<TaskCard order={r.data.order} refresh={r.refresh}/>}</AdminShell>;}
