import type {ReactNode} from 'react';
import {NavLink,Link} from 'react-router-dom';
export function SymbolIcon({name='box'}:{name?:string}){
 const paths:Record<string,ReactNode>={box:<><path d="m3 7 9-5 9 5-9 5Z" fill="currentColor" opacity=".65" stroke="none"/><path d="m3 7 9 5v10l-9-5Z" fill="currentColor" opacity=".82" stroke="none"/><path d="m12 12 9-5v10l-9 5Z" fill="currentColor" stroke="none"/><path d="m8 4.3 9 5V14" stroke="white" strokeWidth="2.5" opacity=".85"/></>,home:<><path d="m3 10 9-8 9 8v11H3Z"/><path d="M9 21v-8h6v8"/></>,order:<><rect x="5" y="3" width="14" height="19" rx="2"/><path d="M9 8h6M9 12h6M9 16h4"/></>,room:<><path d="M5 22V3h14v19M8 3l8-1v20l-8-2Z"/><path d="M12 12h1"/></>,person:<><circle cx="12" cy="6" r="3"/><path d="m9 11-3 6M9 11l6 2 4 4M10 12l1 5-4 5M11 17l6 5"/></>,help:<><circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 5M12 17h.01"/></>,plane:<><path d="m2 10 20-8-8 20-4-8-8-4Z"/><path d="m10 14 7-7"/></>,phone:<path d="M5 3h4l2 5-3 2a13 13 0 0 0 6 6l2-3 5 2v4c0 2-3 3-5 2C8 19 4 15 2 7 1 5 3 3 5 3Z"/>};
 return <svg className={`symbol-icon icon-${name}`} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.box}</svg>;
}
export function CampusRail(){return <aside className="campus-rail"><Link className="rail-brand" to="/" aria-label="青岛科技大学崂山校区校园快递首页"><span className="brand-emblem" aria-hidden="true">QUST</span><span className="rail-brand-copy"><strong>青岛科技大学</strong><small>QINGDAO UNIVERSITY<br/>OF SCIENCE & TECHNOLOGY</small></span></Link><div className="rail-campus"><span className="campus-dot"/>崂山校区<span>CampusDrop</span></div><p className="rail-label">校园服务</p><nav aria-label="主导航">{[['/','home','首页'],['/parcel/new','box','我要下单'],['/orders','order','我的订单'],['/profile','room','我的寝室'],['/guide','order','配送说明'],['/help','help','常见问题'],['/contact','phone','配送联系']].map(([path,icon,label])=><NavLink key={path} to={path} end={path==='/'}><SymbolIcon name={icon}/><span>{label}</span><b aria-hidden="true">›</b></NavLink>)}</nav><div className="rail-bottom"><Link className="rail-admin" to="/admin/login"><SymbolIcon name="person"/>管理员工作台<span aria-hidden="true">↗</span></Link><div className="rail-landscape"><p>在青科大<br/><strong>让期待，近一点。</strong></p><span>LAOSHAN CAMPUS / QUST</span></div><p className="rail-disclosure">独立校园服务 · 非学校官方产品</p></div></aside>;}
export function ServicePages({kind}:{kind:'guide'|'help'|'contact'}){
 return <section className="information-page"><p className="eyebrow">CAMPUSDROP / 校园服务</p><h1>{kind==='guide'?'配送说明':kind==='help'?'常见问题':'配送联系'}</h1>{kind==='guide'?<><p>在校园里，让包裹更快抵达你的身边。当前为模拟服务，所有资金操作均未发生真实扣款。</p><div className="rate-grid">{['小件 · 楼下 / 2元','小件 · 到寝 / 3元','大件 · 楼下 / 5元','大件 · 到寝 / 7元'].map(t=><article key={t}><SymbolIcon/><strong>{t}</strong></article>)}</div><h2>简单几步，安排配送</h2><ol><li>填写寝室资料，手动登记正确的取件码。</li><li>选择大小件和配送方式，确认服务端报价后模拟支付。</li><li>管理员接单后，在订单中查看联系电话及配送进度。</li></ol><p>楼下升级到寝室：小件补1元，大件补2元。没有公开承诺的营业时段、实时物流追踪或到达时间预测。</p><Link to="/handoff-rules">查看包裹交接与退单规则 →</Link></>:kind==='help'?<>{[['取件码怎么填写？','请手动输入，例如 87-5-2739。系统会去除前后空格，不会自动读取菜鸟短信或账户。'],['为什么有模拟支付？','当前版本用于测试流程，支付、补款、退款及打赏均不会发生真实资金流转。'],['取消后订单还在？','取消配送会保留订单和退款记录，你可以确认退款信息后再隐藏订单。'],['配送员退单后怎么办？','订单会重新进入接单市场。如果包裹已取出，须先完成归还与另一管理员核验。'],['怎样切换账号？','点击页面上的“退出登录 / 切换账号”，退出后回到登录页。']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</>:<><div className="contact-illustration"><SymbolIcon name="phone"/></div><h2>通过订单联系接单人</h2><p>进入“我的订单”，接单后会展示配送员的联系电话，可直接拨打。异常原因、归还交接和退单进度也会在订单中显示。</p><Link className="button" to="/orders">前往我的订单</Link><p className="muted">尚未接单时请等待或刷新订单。平台暂未开设在线客服、热线或即时聊天，请勿使用测试账号中的占位电话号码联系他人。</p><Link to="/help">查看常见问题 →</Link></>}</section>;
}
