import {useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {api} from './api';
import {useResource} from './student-delivery';
export function RecoveryPage(){const [kind,setKind]=useState('student'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);try{const r=await api<{message:string}>('/auth/recovery/reset','POST',{kind,username:form.get('username'),code:String(form.get('code')).trim(),newPassword:form.get('password')});setMessage(r.message);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section><h1>找回账号密码</h1><p>使用已保存的一次性恢复码。没有恢复码时，请由超级管理员核验身份后签发；仅知道手机号或用户名不能重置密码。</p><form onSubmit={submit}><label>账号类型<select value={kind} onChange={e=>setKind(e.target.value)}><option value="student">学生</option><option value="admin">管理员</option></select></label><label>用户名<input name="username" required autoComplete="username"/></label><label>恢复码<input name="code" required autoComplete="off" maxLength={64}/></label><label>新密码<input name="password" required type="password" minLength={kind==='admin'?12:6} maxLength={128} autoComplete="new-password"/></label><button disabled={busy}>重置密码</button></form><p role="status">{message}</p><Link to={kind==='admin'?'/admin/login':'/login'}>返回登录</Link></section>;
}
export function RecoveryCode({admin=false}:{admin?:boolean}){const [code,setCode]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);try{const r=await api<{code:string;expiresAt:number}>(admin?'/admin/me/recovery-code':'/me/recovery-code','POST',{currentPassword:form.get('password')});setCode(r.code);setMessage('有效至 '+new Date(r.expiresAt*1000).toLocaleString()+'。请私下保存，不要公开分享。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <details><summary>设置账号恢复码</summary><p>恢复码可重置密码，仅显示一次。重新生成会使旧码失效。</p><form onSubmit={submit}><label>验证当前密码<input name="password" type="password" required autoComplete="current-password"/></label><button disabled={busy}>生成恢复码</button></form>{code&&<code className="identifier">{code}</code>}<p role="status">{message}</p></details>;
}
export function RecoveryAdmin(){const [kind,setKind]=useState('student'),[message,setMessage]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const r=await api<{code:string}>('/admin/recovery/issue','POST',{kind,username:f.get('username'),currentPassword:f.get('password'),identityVerified:f.get('confirmed')==='on'});setCode(r.code);setMessage('恢复码有效15分钟，请通过核验后的私密渠道交给账号本人。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section><h1>账号恢复管理</h1><p>仅超级管理员可用。必须先通过可信渠道核验身份；手填号码不构成身份凭证。超级管理员账号使用本人恢复码或受控离线流程。</p><form onSubmit={submit}><label>账号类型<select value={kind} onChange={e=>setKind(e.target.value)}><option value="student">学生</option><option value="admin">普通管理员</option></select></label><label>目标用户名<input name="username" required/></label><label>当前超级管理员密码<input name="password" type="password" required autoComplete="current-password"/></label><label className="check"><input type="checkbox" name="confirmed" required/>已独立核验账号本人身份</label><button disabled={busy}>签发短期恢复码</button></form>{code&&<code className="identifier">{code}</code>}<p role="status">{message}</p></section>;
}
export function ErrorMonitor(){const r=useResource<{events:{requestId:string;route:string;category:string;status:number;createdAt:number}[];counts:{category:string;count:number}[]}>('/admin/errors');return <section><h1>服务错误监控</h1><p>仅记录错误分类、脱敏路由和问题编号。保留最近7天且最多1000条，当前展示最新100条；不含账号、密码、电话、请求正文或完整错误堆栈。</p><button onClick={()=>void r.refresh()}>刷新监控</button><p role="alert">{r.error}</p>{r.data?.counts.map(c=><p key={c.category}>{c.category}：24小时内 {c.count} 次</p>)}{r.data?.events.length===0&&<p>暂无已记录的服务错误。</p>}{r.data?.events.map(e=><article className="parcel-card" key={e.requestId}><strong>{e.category} · HTTP {e.status}</strong><p>{e.route}</p><code>{e.requestId}</code><small>{new Date(e.createdAt*1000).toLocaleString()}</small></article>)}</section>;}
