import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {api} from './api';
import {useResource} from './student-delivery';
import {ConfirmAction} from './components';
import type {Order} from '../shared/delivery';
import {STATUS_LABELS} from '../shared/delivery';
import type {Ticket,TicketMessage,InboxMessage} from '../shared/support';
export function RoundHistory({order}:{order:Order}){return <div className="round-history"><p><strong>第 {(order.returnCount??0)+1} 轮配送</strong> · 已退回 {order.returnCount??0} 次 · {order.status==='WAITING_PICKUP'?(order.hasAssignee?'已接单，待取件':'接单市场等待接单'):order.status==='COMPLETED'?'已完成':order.status.startsWith('DELIVERED')?'已送达，待学生确认':STATUS_LABELS[order.status]}</p>{!!order.returnHistory?.length&&<details><summary>查看全部退回理由（{order.returnHistory.length}轮）</summary><ol>{order.returnHistory.map((h,i)=><li key={i}><strong>第 {i+1} 轮 · {h.adminName}</strong><p>{h.reason}</p><small>{new Date(h.createdAt*1000).toLocaleString()}</small></li>)}</ol></details>}</div>;}
export function MessageLink(){const r=useResource<{unread:number}>('/messages');useEffect(()=>{const t=setInterval(()=>{if(!document.hidden)void r.refresh();},30000);return()=>clearInterval(t);},[r.refresh]);return <Link to="/messages">消息{r.data?.unread?` (${r.data.unread})`:''}</Link>;}
export function Inbox(){const [before,setBefore]=useState(''),[back,setBack]=useState<string[]>([]);const r=useResource<{messages:InboxMessage[];nextCursor:number|null;unread:number}>(`/messages${before?'?before='+before:''}`);const [error,setError]=useState('');
 async function read(id?:number){try{await api(id?`/messages/${id}/read`:'/messages/read-all','POST',id?undefined:{confirmed:true});await r.refresh();}catch(e){setError((e as Error).message);}}
 return <section><h1>站内消息</h1><p>未读 {r.data?.unread??0} 条。接单、退单、送达、签收和售后更新会在这里保留。</p><div className="actions"><button onClick={()=>void r.refresh()}>刷新消息</button><button className="secondary" onClick={()=>void read()}>全部标为已读</button></div><p role="alert">{error||r.error}</p>{r.data?.messages.length===0&&<p>暂无消息。</p>}{r.data?.messages.map(m=><article className="parcel-card" key={m.id}><strong>{!m.readAt?'● ':''}{m.title}</strong><p>{new Date(m.createdAt*1000).toLocaleString()}</p><div className="actions"><Link to={m.kind.startsWith('TICKET')?'/tickets':`/orders/${m.orderId}`} onClick={()=>void read(m.id)}>查看详情</Link>{!m.readAt&&<button className="text-button" onClick={()=>void read(m.id)}>标为已读</button>}</div></article>)}<div className="actions"><button disabled={!back.length} onClick={()=>{setBefore(back.at(-1)!);setBack(back.slice(0,-1));}}>上一页</button><button disabled={!r.data?.nextCursor} onClick={()=>{setBack([...back,before]);setBefore(String(r.data!.nextCursor));}}>下一页</button></div></section>;}
const labels:Record<string,string>={OPEN:'待受理',IN_PROGRESS:'处理中',RESOLVED:'已提出解决方案',CLOSED:'已关闭'};
function LinkedOrder({ticket,admin=false}:{ticket:Ticket;admin?:boolean}){
 const detail=ticket.orderContext;
 return <aside className="ticket-order-context"><strong>关联订单 · {ticket.orderId.slice(0,8)}</strong>{detail&&<><p>{detail.building} · {detail.room}</p><p>{detail.station} · {STATUS_LABELS[detail.status]}</p></>}<Link to={`${admin?'/admin':''}/orders/${ticket.orderId}`}>查看关联订单详情</Link></aside>;
}
const ticketCategories:Record<string,string>={NOT_RECEIVED:'未收到包裹',DAMAGED:'包裹破损',WRONG_DELIVERY:'配送错误',REFUND:'退款问题',OTHER:'其他问题'};
export function TicketList({admin=false}:{admin?:boolean}){const [before,setBefore]=useState(''),[back,setBack]=useState<string[]>([]);const r=useResource<{tickets:Ticket[];nextCursor:string|null}>(`${admin?'/admin':''}/tickets${before?'?before='+encodeURIComponent(before):''}`);return <section><h1>{admin?'售后处理工作台':'我的售后工单'}</h1><p>{admin?'仅展示当前授权订单相关工单。请先受理、回复处理方案，再标记已解决。':'在订单详情中发起售后；收到处理方案后可关闭或重新打开工单。'}</p><button onClick={()=>void r.refresh()}>刷新工单</button><p role="alert">{r.error}</p>{r.data?.tickets.length===0&&<p>暂无工单。</p>}{r.data?.tickets.map(t=><article key={t.id} className="parcel-card"><strong>{t.subject}</strong><p>{ticketCategories[t.category]} · {labels[t.status]}</p><LinkedOrder ticket={t} admin={admin}/><Link to={`${admin?'/admin':''}/tickets/${t.id}`}>查看与回复</Link></article>)}<div className="actions"><button disabled={!back.length} onClick={()=>{setBefore(back.at(-1)!);setBack(back.slice(0,-1));}}>上一页</button><button disabled={!r.data?.nextCursor} onClick={()=>{setBack([...back,before]);setBefore(r.data!.nextCursor!);}}>下一页</button></div></section>;}
export function TicketNew(){const [query]=useSearchParams(),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[id,setId]=useState(''),[created,setCreated]=useState<Ticket|null>(null);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const r=await api<{ticket:Ticket}>('/tickets','POST',{orderId:query.get('orderId'),category:f.get('category'),subject:f.get('subject'),body:f.get('body')});setId(r.ticket.id);setCreated(r.ticket);setMessage('工单已提交，请在工单中查看回复。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section><h1>发起售后</h1><p>请描述订单问题，不填写密码或额外取件凭证。售后处理不会自动发起真实退款。</p>{!id&&<form onSubmit={submit}><label>问题类型<select name="category"><option value="NOT_RECEIVED">未收到包裹</option><option value="DAMAGED">包裹破损</option><option value="WRONG_DELIVERY">配送错误</option><option value="REFUND">退款问题</option><option value="OTHER">其他问题</option></select></label><label>问题标题<input name="subject" required maxLength={80}/></label><label>详细说明<textarea name="body" required maxLength={1000}/></label><button disabled={busy}>提交售后工单</button></form>}<p role="status">{message}</p>{created&&<LinkedOrder ticket={created}/>}<p>{!id&&query.get('orderId')?`当前订单：${query.get('orderId')?.slice(0,8)}`:''}</p>{id&&<Link to={`/tickets/${id}`}>打开工单</Link>}<p><Link to="/tickets">查看已有工单</Link></p></section>;}
export function TicketDetail({admin=false}:{admin?:boolean}){const {id}=useParams(),base=`${admin?'/admin':''}/tickets/${id}`;const r=useResource<{ticket:Ticket;messages:TicketMessage[]}>(base);const [text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function act(status?:string){if(!r.data)return;setBusy(true);try{await api(base+(status?'/status':'/messages'),'POST',status?{status,version:r.data.ticket.version,confirmed:true}:{body:text,version:r.data.ticket.version});setText('');setError('');await r.refresh();}catch(e){setError((e as Error).message);await r.refresh();}finally{setBusy(false);}}
 const t=r.data?.ticket;return <section><h1>售后工单详情</h1><p role="alert">{error||r.error}</p>{t&&<><h2>{t.subject}</h2><p>{ticketCategories[t.category]} · {labels[t.status]}</p><LinkedOrder ticket={t} admin={admin}/>{r.data?.messages.map(m=><article className="parcel-card" key={m.id}><strong>{m.actorKind==='ADMIN'?'管理员':'学生'}</strong><p>{m.body}</p><small>{new Date(m.createdAt*1000).toLocaleString()}</small></article>)}{t.status!=='CLOSED'&&<><label>补充说明或回复<textarea value={text} maxLength={1000} onChange={e=>setText(e.target.value)}/></label><button disabled={busy||!text.trim()} onClick={()=>void act()}>发送回复</button></>}<div className="actions">{(admin?(t.status==='OPEN'?['IN_PROGRESS']:t.status==='IN_PROGRESS'?['RESOLVED']:[]):t.status==='RESOLVED'?['CLOSED','OPEN']:[]).map(status=><ConfirmAction key={status} label={{IN_PROGRESS:'受理工单',RESOLVED:'标记已解决',CLOSED:'确认关闭',OPEN:'问题未解决，重新打开'}[status]!} title="确认更新工单状态？" busy={busy} onConfirm={()=>act(status)}><p>状态变更会通知学生，并保留处理记录。请先写明处理方案。</p></ConfirmAction>)}</div></>}</section>;}
export function BulkPickupView({orders}:{orders:Order[]}){const generation=useRef(0);const [ids,setIds]=useState<string[]>([]),[items,setItems]=useState<{id:string;pickupCode:string;buildingName:string;roomNo:string;phone:string;stationName:string;note:string}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);const signature=orders.map(o=>o.id+':'+o.version).join(',');useEffect(()=>{generation.current++;setItems([]);setIds([]);return()=>{generation.current++;};},[signature]);useEffect(()=>{const hide=()=>{if(document.hidden){generation.current++;setItems([]);}};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[]);useEffect(()=>{if(!items.length)return;const hide=()=>{if(document.hidden)setItems([]);};document.addEventListener('visibilitychange',hide);const timer=setTimeout(()=>setItems([]),30000);return()=>{clearTimeout(timer);document.removeEventListener('visibilitychange',hide);};},[items]);async function show(){const version=++generation.current;setBusy(true);setItems([]);try{const r=await api<{items:typeof items}>('/admin/orders/bulk-pickup','POST',{orderIds:ids,confirmed:true});if(!document.hidden&&version===generation.current)setItems(r.items);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="bulk-pickup" onToggle={e=>{if(!e.currentTarget.open){generation.current++;setItems([]);}}}><summary>批量取件清单（最多20单）</summary><p>仅选择当前页已授权的未结束订单，每批最多20单。每次查看记录脱敏审计，30秒或切换页面后隐藏。</p><div className="actions"><button className="secondary" disabled={busy} onClick={()=>{generation.current++;setItems([]);setIds(orders.filter(o=>!['CANCELLED','COMPLETED'].includes(o.status)).slice(0,20).map(o=>o.id));}}>全选本页（最多20单）</button><button className="text-button" disabled={busy} onClick={()=>{generation.current++;setItems([]);setIds([]);}}>清空取件选择</button></div>{orders.filter(o=>!['CANCELLED','COMPLETED'].includes(o.status)).map(o=><label className="check" key={o.id}><input type="checkbox" checked={ids.includes(o.id)} disabled={!ids.includes(o.id)&&ids.length>=20} onChange={e=>{generation.current++;setItems([]);setIds(e.target.checked?[...ids,o.id]:ids.filter(id=>id!==o.id));}}/>{o.id.slice(0,8)} · {o.dormSnapshot.buildingName} {o.dormSnapshot.roomNo}</label>)}<button disabled={busy||!ids.length} onClick={()=>void show()}>查看所选取件信息（{ids.length}）</button><button className="secondary" onClick={()=>{generation.current++;setItems([]);}}>立即隐藏</button><p role="alert">{error}</p>{items.map(i=><article className="parcel-card" key={i.id}><strong className="pickup-code">{i.pickupCode}</strong><p>{i.stationName}</p><p>{i.buildingName} · {i.roomNo} · {i.phone}</p><p>{i.note}</p></article>)}</details>;}
